In [49]:
import pandas as pd

csv_paths = [
    "2025_1.csv",
    "2025_0.csv"
]
dfs = []
for f in csv_paths:
    dfs.append(pd.read_csv(
        f,
        sep=";",                # semicolon separator
        quotechar='"',          # handle quoted fields properly
        decimal=",",            # interpret ',' as decimal
        engine="python",        # more forgiving parser
        dtype=str               # read everything as string first to avoid type issues
    ))
df = pd.concat(dfs, ignore_index=True)
df["Kwota operacji"] = (
    df["Kwota operacji"]
    .astype(str)
    .str.replace(" ", "", regex=False)   # remove spaces
    .str.replace(",", ".", regex=False)  # handle comma as decimal if needed
    .astype(float)
)

In [50]:
df = df[df["Kwota operacji"] < 0]
df

,Data księgowania,Data waluty,Nadawca / Odbiorca,Adres nadawcy / odbiorcy,Rachunek źródłowy,Rachunek docelowy,Tytułem,Kwota operacji,Waluta,Numer referencyjny,Typ operacji,Kategoria
0,31.12.2025,31.12.2025,CERAMIQ.PL WARSZAWA,22844303 73101723 *********2797252,'69124011121111001132898240,NaN,*********2797252,-521.01,PLN,'C992536510261152,TRANSAKCJA KARTĄ PŁATNICZĄ,Artykuły dekoracyjne
1,31.12.2025,31.12.2025,AUTOPAY S.A.,"E-WLOCZYKIJKI.P POWSTANCOW WARSZAWY 6,SOPOT",'69124011121111001132898240,NaN,BLIK REF 92877523732,-250.00,PLN,'C992536510217603,PŁATNOŚĆ BLIK,Bez kategorii
2,31.12.2025,31.12.2025,SKLEP JACEK WARSZAWA,04630729 020200600000001 *********2797252,'69124011121111001132898240,NaN,*********2797252,-48.93,PLN,'C992536508177445,TRANSAKCJA KARTĄ PŁATNICZĄ,Artykuły spożywcze
3,31.12.2025,31.12.2025,JMP S.A. BIEDRONKA 6121WARSZAWA,87809562 496710614116 *********2797252,'69124011121111001132898240,NaN,*********2797252,-253.51,PLN,'C992536508696773,TRANSAKCJA KARTĄ PŁATNICZĄ,Artykuły spożywcze
4,30.12.2025,30.12.2025,KIP,"CENTRUMALMA.PL PLAC ANDERSA 3 73,POZNAN",'69124011121111001132898240,NaN,BLIK REF 92857136012,-400.00,PLN,'C992536416482080,PŁATNOŚĆ BLIK,Zakupy przez internet
...,...,...,...,...,...,...,...,...,...,...,...,...
1632,02.01.2025,31.12.2024,BANK PEKAO S.A.,CENTRALA-OŚRODEK OPERACJI KART ul. Żubra 1 01-...,'69124011121111001132898240,'53124000270999999999999999,ROZLICZENIE TRANSAKCJINA KARTĘ **** **** 2279 ...,-70.85,PLN,'0324123160060287,PRZELEW,Inne
1633,02.01.2025,02.01.2025,PAYPRO S.A.,"HTTP://X-KOM.PL Pastelowa 8,Poznan",'69124011121111001132898240,NaN,BLIK REF 85608122599,-279.99,PLN,'C992500214795014,PŁATNOŚĆ BLIK,Sprzęt AGD i RTV
1635,02.01.2025,02.01.2025,PAYU,"WWW.NTFY.PL Grunwaldzka 186,Poznan",'69124011121111001132898240,NaN,BLIK REF 85606544281,-814.86,PLN,'C992500204602014,PŁATNOŚĆ BLIK,Artykuły spożywcze
1637,01.01.2025,31.12.2024,LA POSE WARSZAWA,28102572 72760601 *********2797252,'69124011121111001132898240,NaN,*********2797252,-20.00,PLN,'C992436621433872,TRANSAKCJA KARTĄ PŁATNICZĄ,Restauracje i kawiarnie
1638,01.01.2025,01.01.2025,UBR* PENDING.UBER.COM AMSTERDAM,35486422 020320555 *********2797252,'69124011121111001132898240,NaN,*********2797252,-81.91,PLN,'C992500103535538,TRANSAKCJA KARTĄ PŁATNICZĄ,Taxi

In [51]:
df.groupby("Kategoria")["Kwota operacji"].sum()

Kategoria
Alkohol                                      -112.33
Artykuły dekoracyjne                         -782.21
Artykuły spożywcze                         -24157.83
Bez kategorii                             -101359.07
Bilety lotnicze                             -2292.12
Czynsz                                     -10232.04
Dodatki, biżuteria                           -763.90
Fotografia                                    -27.70
Gazety lub czasopisma                         -10.49
Hobby                                       -1206.78
Hotele                                      -6237.19
Inne                                        -2082.55
Internet, TV, telefon                       -7021.30
Kino i teatr                                -2055.07
Kosmetyki                                   -2743.98
Książki                                      -115.91
Lekarstwa                                   -3796.10
Multimedia                                  -1012.77
Naprawy i remonty                           -1884.81
Ogród                                       -1653.50
Opieka medyczna                             -2613.60
Opłaty bankowe                                -81.65
Paliwo                                      -3317.61
Papierosy                                     -23.41
Podróże                                    -16419.27
Prezenty, upominki                            -69.70
Przelew wewnętrzny                         -98859.50
Prąd                                          -24.50
Puby i kluby                                 -453.00
Restauracje i kawiarnie                    -13882.19
Sport                                       -3357.46
Sprzątanie                                   -283.92
Sprzęt AGD i RTV                            -4408.98
Spłata kredytu / pożyczki                  -41905.78
Taxi                                        -2362.02
Transport publiczny                          -203.29
Ubezpieczenia                                -535.68
Ubrania                                     -5718.81
Uroda, fryzjer, kosmetyczka                  -960.00
Usługi (pralnia, krawiec, szewc,...)         -689.58
Wyposażenie                                -47670.73
Wypłata z bankomatu                         -6613.92
Wypłata z rachunku                         -21000.00
Zakupy przez internet                      -46327.09
Założenie lokaty, zakup funduszy, akcji     -1662.33
Zwierzęta domowe                             -135.96
Name: Kwota operacji, dtype: float64

In [52]:
df[df["Kategoria"] == 'Inne']

,Data księgowania,Data waluty,Nadawca / Odbiorca,Adres nadawcy / odbiorcy,Rachunek źródłowy,Rachunek docelowy,Tytułem,Kwota operacji,Waluta,Numer referencyjny,Typ operacji,Kategoria
25,27.12.2025,27.12.2025,SKYCASH POLAND S.A.,NaN,'69124011121111001132898240,'05124040960003000000000001,"Bilet jednorazowy przesiadkowy, 75-min, normal...",-4.40,PLN,'PEOREFT022188152,TRANSAKCJA PEOPAY,Inne
27,26.12.2025,26.12.2025,SKYCASH POLAND S.A.,NaN,'69124011121111001132898240,'05124040960003000000000001,"Bilet dobowy, normalny Warszawa N 15,00 PLN e8...",-15.00,PLN,'PEOREFT022178179,TRANSAKCJA PEOPAY,Inne
52,19.12.2025,19.12.2025,SKYCASH POLAND S.A.,NaN,'69124011121111001132898240,'05124040960003000000000001,"Bilet dobowy, normalny Warszawa N 15,00 PLN f9...",-15.00,PLN,'PEOREFT022072338,TRANSAKCJA PEOPAY,Inne
63,16.12.2025,16.12.2025,SKYCASH POLAND S.A.,NaN,'69124011121111001132898240,'05124040960003000000000001,"Bilet dobowy, normalny Warszawa N 15,00 PLN a1...",-15.00,PLN,'PEOREFT021947684,TRANSAKCJA PEOPAY,Inne
65,16.12.2025,16.12.2025,SKYCASH POLAND S.A.,NaN,'69124011121111001132898240,'05124040960003000000000001,"Bilet 20-min, normalny Warszawa N 3,40 PLN b17...",-3.40,PLN,'PEOREFT021944064,TRANSAKCJA PEOPAY,Inne
...,...,...,...,...,...,...,...,...,...,...,...,...
1590,20.01.2025,18.01.2025,SKYCASH POLAND S.A.,NaN,'69124011121111001132898240,'05124040960003000000000001,"Bilet jednorazowy przesiadkowy, 75-min, normal...",-8.80,PLN,'PEOREFT013865013,TRANSAKCJA PEOPAY,Inne
1594,18.01.2025,18.01.2025,SKYCASH POLAND S.A.,NaN,'69124011121111001132898240,'05124040960003000000000001,"Bilet jednorazowy przesiadkowy, 75-min, normal...",-8.80,PLN,'PEOREFT013863592,TRANSAKCJA PEOPAY,Inne
1595,18.01.2025,18.01.2025,SKYCASH POLAND S.A.,NaN,'69124011121111001132898240,'05124040960003000000000001,"Bilet jednorazowy przesiadkowy, 75-min, normal...",-8.80,PLN,'PEOREFT013860938,TRANSAKCJA PEOPAY,Inne
1614,14.01.2025,14.01.2025,SKYCASH POLAND S.A.,NaN,'69124011121111001132898240,'05124040960003000000000001,"Bilet jednorazowy przesiadkowy, 75-min, normal...",-4.40,PLN,'PEOREFT013759185,TRANSAKCJA PEOPAY,Inne
1632,02.01.2025,31.12.2024,BANK PEKAO S.A.,CENTRALA-OŚRODEK OPERACJI KART ul. Żubra 1 01-...,'69124011121111001132898240,'53124000270999999999999999,ROZLICZENIE TRANSAKCJINA KARTĘ **** **** 2279 ...,-70.85,PLN,'0324123160060287,PRZELEW,Inne

In [53]:
category_sums = df.groupby("Kategoria")["Kwota operacji"].sum().reset_index()
category_sums = category_sums.sort_values("Kwota operacji", ascending=False)

df_merged = df.merge(category_sums, on="Kategoria", suffixes=("", "_category_sum"))

df_sorted = df_merged.sort_values(
    by=["Kwota operacji_category_sum", "Kwota operacji"], 
    ascending=[True, True]
)
df_sorted

,Data księgowania,Data waluty,Nadawca / Odbiorca,Adres nadawcy / odbiorcy,Rachunek źródłowy,Rachunek docelowy,Tytułem,Kwota operacji,Waluta,Numer referencyjny,Typ operacji,Kategoria,Kwota operacji_category_sum
1236,28.03.2025,28.03.2025,MINISTERSTWO FINANSOW,"MF/TWOJ E-PIT P SWIETOKRZYSKA 12,WARSZAWA",'69124011121111001132898240,NaN,BLIK REF 87310704119,-40133.12,PLN,'C992508712398997,PŁATNOŚĆ BLIK,Bez kategorii,-101359.07
1015,19.05.2025,19.05.2025,ZIELINSKI ART,WROCŁAWSKI PARK BIZNESU; BIERUTOWSK A 57-59; 5...,'69124011121111001132898240,'11114020040000380281241961,"Kamil Długosz, pierścionek zaręczynowy z mossa...",-19870.00,PLN,'041255J602808695,REALIZACJA PŁATNOŚCI PEOPAY,Bez kategorii,-101359.07
184,20.11.2025,20.11.2025,VOX JANKI,NaN,'69124011121111001132898240,'61114011240000468232001012,WISZNIEWSKA.32,-6801.33,PLN,'04125BK621205776,REALIZACJA PŁATNOŚCI PEOPAY,Bez kategorii,-101359.07
441,22.09.2025,22.09.2025,STOMEBLE,NaN,'69124011121111001132898240,'85102010260000150206910600,zaliczka umowa 09/01,-4600.00,PLN,'041259M602203334,REALIZACJA PŁATNOŚCI PEOPAY,Bez kategorii,-101359.07
1169,12.04.2025,12.04.2025,ELECZKA TOMASZ BAWOROWSKI,NaN,'69124011121111001132898240,'11105001451000009735800600,Kamil Długosz,-3650.00,PLN,'041254C603502801,REALIZACJA PŁATNOŚCI PEOPAY,Bez kategorii,-101359.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
958,27.05.2025,27.05.2025,STUDIO FOTOGRAFICZNE MIWARSZAWA,03316445 014590800000001 *********2797252,'69124011121111001132898240,NaN,*********2797252,-27.70,PLN,'C992514712788592,TRANSAKCJA KARTĄ PŁATNICZĄ,Fotografia,-27.70
1193,05.04.2025,05.04.2025,PGE PARKING 4 WARSZAWA,29283633 2101756188 *********2797252,'69124011121111001132898240,NaN,*********2797252,-20.00,PLN,'C992509513646657,TRANSAKCJA KARTĄ PŁATNICZĄ,Prąd,-24.50
140,01.12.2025,01.12.2025,2THELOO WAW NAYAX WARSZAWA,71896902 2102031833 *********2797252,'69124011121111001132898240,NaN,*********2797252,-4.50,PLN,'C992533520813758,TRANSAKCJA KARTĄ PŁATNICZĄ,Prąd,-24.50
688,12.07.2025,11.07.2025,MANOLIAKIS NIKOLAOS PALIA POLI R,01833522 140833526 *********2797252,'69124011121111001132898240,NaN,*********2797252,-23.41,PLN,'C992519221983352,TRANSAKCJA KARTĄ PŁATNICZĄ,Papierosy,-23.41
141,01.12.2025,01.12.2025,RELAY 33301 WARSZAWA,01473834 006258600000058 *********2797252,'69124011121111001132898240,NaN,*********2797252,-10.49,PLN,'C992533517007134,TRANSAKCJA KARTĄ PŁATNICZĄ,Gazety lub czasopisma,-10.49

In [54]:
df_sorted["kat"] = ""

cols_first = [
    "Data księgowania",
    "Nadawca / Odbiorca",
    "Adres nadawcy / odbiorcy",
    "Tytułem",
    "Kwota operacji",
    "Kategoria",
    "kat"
]
other_cols = [c for c in df_sorted.columns if c not in cols_first]

df_sorted = df_sorted[cols_first + other_cols]
df_sorted

,Data księgowania,Nadawca / Odbiorca,Adres nadawcy / odbiorcy,Tytułem,Kwota operacji,Kategoria,kat,Data waluty,Rachunek źródłowy,Rachunek docelowy,Waluta,Numer referencyjny,Typ operacji,Kwota operacji_category_sum
1236,28.03.2025,MINISTERSTWO FINANSOW,"MF/TWOJ E-PIT P SWIETOKRZYSKA 12,WARSZAWA",BLIK REF 87310704119,-40133.12,Bez kategorii,,28.03.2025,'69124011121111001132898240,NaN,PLN,'C992508712398997,PŁATNOŚĆ BLIK,-101359.07
1015,19.05.2025,ZIELINSKI ART,WROCŁAWSKI PARK BIZNESU; BIERUTOWSK A 57-59; 5...,"Kamil Długosz, pierścionek zaręczynowy z mossa...",-19870.00,Bez kategorii,,19.05.2025,'69124011121111001132898240,'11114020040000380281241961,PLN,'041255J602808695,REALIZACJA PŁATNOŚCI PEOPAY,-101359.07
184,20.11.2025,VOX JANKI,NaN,WISZNIEWSKA.32,-6801.33,Bez kategorii,,20.11.2025,'69124011121111001132898240,'61114011240000468232001012,PLN,'04125BK621205776,REALIZACJA PŁATNOŚCI PEOPAY,-101359.07
441,22.09.2025,STOMEBLE,NaN,zaliczka umowa 09/01,-4600.00,Bez kategorii,,22.09.2025,'69124011121111001132898240,'85102010260000150206910600,PLN,'041259M602203334,REALIZACJA PŁATNOŚCI PEOPAY,-101359.07
1169,12.04.2025,ELECZKA TOMASZ BAWOROWSKI,NaN,Kamil Długosz,-3650.00,Bez kategorii,,12.04.2025,'69124011121111001132898240,'11105001451000009735800600,PLN,'041254C603502801,REALIZACJA PŁATNOŚCI PEOPAY,-101359.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958,27.05.2025,STUDIO FOTOGRAFICZNE MIWARSZAWA,03316445 014590800000001 *********2797252,*********2797252,-27.70,Fotografia,,27.05.2025,'69124011121111001132898240,NaN,PLN,'C992514712788592,TRANSAKCJA KARTĄ PŁATNICZĄ,-27.70
1193,05.04.2025,PGE PARKING 4 WARSZAWA,29283633 2101756188 *********2797252,*********2797252,-20.00,Prąd,,05.04.2025,'69124011121111001132898240,NaN,PLN,'C992509513646657,TRANSAKCJA KARTĄ PŁATNICZĄ,-24.50
140,01.12.2025,2THELOO WAW NAYAX WARSZAWA,71896902 2102031833 *********2797252,*********2797252,-4.50,Prąd,,01.12.2025,'69124011121111001132898240,NaN,PLN,'C992533520813758,TRANSAKCJA KARTĄ PŁATNICZĄ,-24.50
688,12.07.2025,MANOLIAKIS NIKOLAOS PALIA POLI R,01833522 140833526 *********2797252,*********2797252,-23.41,Papierosy,,11.07.2025,'69124011121111001132898240,NaN,PLN,'C992519221983352,TRANSAKCJA KARTĄ PŁATNICZĄ,-23.41
141,01.12.2025,RELAY 33301 WARSZAWA,01473834 006258600000058 *********2797252,*********2797252,-10.49,Gazety lub czasopisma,,01.12.2025,'69124011121111001132898240,NaN,PLN,'C992533517007134,TRANSAKCJA KARTĄ PŁATNICZĄ,-10.49

In [55]:
mask = df_sorted["Tytułem"].str.contains("bilet", case=False, na=False) & \
       df_sorted["Tytułem"].str.contains("warszawa", case=False, na=False)
df_sorted.loc[mask, "kat"] = "Warszawa bilety"
df_sorted[mask]

,Data księgowania,Nadawca / Odbiorca,Adres nadawcy / odbiorcy,Tytułem,Kwota operacji,Kategoria,kat,Data waluty,Rachunek źródłowy,Rachunek docelowy,Waluta,Numer referencyjny,Typ operacji,Kwota operacji_category_sum
809,21.06.2025,SKYCASH POLAND S.A.,NaN,"Bilet dobowy, normalny Warszawa N 15,00 PLN (4...",-60.0,Inne,Warszawa bilety,21.06.2025,'69124011121111001132898240,'05124040960003000000000001,PLN,'PEOREFT017454194,TRANSAKCJA PEOPAY,-2082.55
324,24.10.2025,SKYCASH POLAND S.A.,NaN,"Bilet dobowy, normalny Warszawa N 15,00 PLN (2...",-30.0,Inne,Warszawa bilety,24.10.2025,'69124011121111001132898240,'05124040960003000000000001,PLN,'PEOREFT020500343,TRANSAKCJA PEOPAY,-2082.55
560,11.08.2025,SKYCASH POLAND S.A.,NaN,"Bilet dobowy, normalny Warszawa N 15,00 PLN (2...",-30.0,Inne,Warszawa bilety,11.08.2025,'69124011121111001132898240,'05124040960003000000000001,PLN,'PEOREFT018602237,TRANSAKCJA PEOPAY,-2082.55
1348,27.02.2025,SKYCASH POLAND S.A.,NaN,"Bilet dobowy, normalny Warszawa N 15,00 PLN (2...",-30.0,Inne,Warszawa bilety,27.02.2025,'69124011121111001132898240,'05124040960003000000000001,PLN,'PEOREFT014752417,TRANSAKCJA PEOPAY,-2082.55
1454,27.01.2025,SKYCASH POLAND S.A.,NaN,"Bilet dobowy, normalny Warszawa N 15,00 PLN (2...",-30.0,Inne,Warszawa bilety,26.01.2025,'69124011121111001132898240,'05124040960003000000000001,PLN,'PEOREFT014022894,TRANSAKCJA PEOPAY,-2082.55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1426,03.02.2025,SKYCASH POLAND S.A.,NaN,"Bilet 20-min, normalny Warszawa N 3,40 PLN 008...",-3.4,Inne,Warszawa bilety,03.02.2025,'69124011121111001132898240,'05124040960003000000000001,PLN,'PEOREFT014192129,TRANSAKCJA PEOPAY,-2082.55
1431,03.02.2025,SKYCASH POLAND S.A.,NaN,"Bilet 20-min, normalny Warszawa N 3,40 PLN d00...",-3.4,Inne,Warszawa bilety,03.02.2025,'69124011121111001132898240,'05124040960003000000000001,PLN,'PEOREFT014190113,TRANSAKCJA PEOPAY,-2082.55
1435,03.02.2025,SKYCASH POLAND S.A.,NaN,"Bilet 20-min, normalny Warszawa N 3,40 PLN 815...",-3.4,Inne,Warszawa bilety,02.02.2025,'69124011121111001132898240,'05124040960003000000000001,PLN,'PEOREFT014174024,TRANSAKCJA PEOPAY,-2082.55
1436,03.02.2025,SKYCASH POLAND S.A.,NaN,"Bilet 20-min, normalny Warszawa N 3,40 PLN e2b...",-3.4,Inne,Warszawa bilety,02.02.2025,'69124011121111001132898240,'05124040960003000000000001,PLN,'PEOREFT014174023,TRANSAKCJA PEOPAY,-2082.55
1099,03.05.2025,SKYCASH POLAND S.A.,NaN,"Bilet 20-min, ulgowy Warszawa U 1,70 PLN bbd14...",-1.7,Inne,Warszawa bilety,03.05.2025,'69124011121111001132898240,'05124040960003000000000001,PLN,'PEOREFT016257359,TRANSAKCJA PEOPAY,-2082.55

In [56]:
mask = df_sorted["Adres nadawcy / odbiorcy"].str.contains("kokonki", case=False, na=False) #& \
       # df_sorted["Tytułem"].str.contains("warszawa", case=False, na=False)
df_sorted.loc[mask, "kat"] = "włóczki"
df_sorted[mask]

,Data księgowania,Nadawca / Odbiorca,Adres nadawcy / odbiorcy,Tytułem,Kwota operacji,Kategoria,kat,Data waluty,Rachunek źródłowy,Rachunek docelowy,Waluta,Numer referencyjny,Typ operacji,Kwota operacji_category_sum
529,18.08.2025,AUTOPAY S.A.,"KOKONKI.PL POWSTANCOW WARSZAWY 6,SOPOT",BLIK REF 90168068316,-678.3,Bez kategorii,włóczki,17.08.2025,'69124011121111001132898240,NaN,PLN,'C992522923976999,PŁATNOŚĆ BLIK,-101359.07
76,13.12.2025,AUTOPAY S.A.,"KOKONKI.PL POWSTANCOW WARSZAWY 6,SOPOT",BLIK REF 92520550131,-129.6,Bez kategorii,włóczki,13.12.2025,'69124011121111001132898240,NaN,PLN,'C992534718925327,PŁATNOŚĆ BLIK,-101359.07

In [57]:
mask = df_sorted["Adres nadawcy / odbiorcy"].str.contains("znanylekarz", case=False, na=False) #& \
       # df_sorted["Tytułem"].str.contains("warszawa", case=False, na=False)
df_sorted.loc[mask, "kat"] = "zdrowie"
df_sorted[mask]

,Data księgowania,Nadawca / Odbiorca,Adres nadawcy / odbiorcy,Tytułem,Kwota operacji,Kategoria,kat,Data waluty,Rachunek źródłowy,Rachunek docelowy,Waluta,Numer referencyjny,Typ operacji,Kwota operacji_category_sum
446,22.09.2025,AUTOPAY S.A.,"ZNANYLEKARZ.PL POWSTANCOW WARSZAWY 6,SOPOT",BLIK REF 90867736026,-250.0,Bez kategorii,zdrowie,21.09.2025,'69124011121111001132898240,NaN,PLN,'C992526419066609,PŁATNOŚĆ BLIK,-101359.07
768,30.06.2025,AUTOPAY S.A.,"ZNANYLEKARZ.PL POWSTANCOW WARSZAWY 6,SOPOT",BLIK REF 89174232855,-250.0,Bez kategorii,zdrowie,29.06.2025,'69124011121111001132898240,NaN,PLN,'C992518013756320,PŁATNOŚĆ BLIK,-101359.07
1415,10.02.2025,AUTOPAY S.A.,"ZNANYLEKARZ.PL Powstancow Warszawy 6,Sopot",BLIK REF 86364389184,-250.0,Bez kategorii,zdrowie,09.02.2025,'69124011121111001132898240,NaN,PLN,'C992504012988505,PŁATNOŚĆ BLIK,-101359.07
378,10.10.2025,AUTOPAY S.A.,"ZNANYLEKARZ.PL POWSTANCOW WARSZAWY 6,SOPOT",BLIK REF 91232683630,-250.0,Opieka medyczna,zdrowie,10.10.2025,'69124011121111001132898240,NaN,PLN,'C992528314702047,PŁATNOŚĆ BLIK,-2613.60
1467,24.01.2025,AUTOPAY S.A.,"ZNANYLEKARZ.PL Powstancow Warszawy 6,Sopot",BLIK REF 86039150462,-250.0,Opieka medyczna,zdrowie,23.01.2025,'69124011121111001132898240,NaN,PLN,'C992502321477817,PŁATNOŚĆ BLIK,-2613.60

In [58]:
df_sorted[df_sorted["kat"] == ""]

,Data księgowania,Nadawca / Odbiorca,Adres nadawcy / odbiorcy,Tytułem,Kwota operacji,Kategoria,kat,Data waluty,Rachunek źródłowy,Rachunek docelowy,Waluta,Numer referencyjny,Typ operacji,Kwota operacji_category_sum
1236,28.03.2025,MINISTERSTWO FINANSOW,"MF/TWOJ E-PIT P SWIETOKRZYSKA 12,WARSZAWA",BLIK REF 87310704119,-40133.12,Bez kategorii,,28.03.2025,'69124011121111001132898240,NaN,PLN,'C992508712398997,PŁATNOŚĆ BLIK,-101359.07
1015,19.05.2025,ZIELINSKI ART,WROCŁAWSKI PARK BIZNESU; BIERUTOWSK A 57-59; 5...,"Kamil Długosz, pierścionek zaręczynowy z mossa...",-19870.00,Bez kategorii,,19.05.2025,'69124011121111001132898240,'11114020040000380281241961,PLN,'041255J602808695,REALIZACJA PŁATNOŚCI PEOPAY,-101359.07
184,20.11.2025,VOX JANKI,NaN,WISZNIEWSKA.32,-6801.33,Bez kategorii,,20.11.2025,'69124011121111001132898240,'61114011240000468232001012,PLN,'04125BK621205776,REALIZACJA PŁATNOŚCI PEOPAY,-101359.07
441,22.09.2025,STOMEBLE,NaN,zaliczka umowa 09/01,-4600.00,Bez kategorii,,22.09.2025,'69124011121111001132898240,'85102010260000150206910600,PLN,'041259M602203334,REALIZACJA PŁATNOŚCI PEOPAY,-101359.07
1169,12.04.2025,ELECZKA TOMASZ BAWOROWSKI,NaN,Kamil Długosz,-3650.00,Bez kategorii,,12.04.2025,'69124011121111001132898240,'11105001451000009735800600,PLN,'041254C603502801,REALIZACJA PŁATNOŚCI PEOPAY,-101359.07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
958,27.05.2025,STUDIO FOTOGRAFICZNE MIWARSZAWA,03316445 014590800000001 *********2797252,*********2797252,-27.70,Fotografia,,27.05.2025,'69124011121111001132898240,NaN,PLN,'C992514712788592,TRANSAKCJA KARTĄ PŁATNICZĄ,-27.70
1193,05.04.2025,PGE PARKING 4 WARSZAWA,29283633 2101756188 *********2797252,*********2797252,-20.00,Prąd,,05.04.2025,'69124011121111001132898240,NaN,PLN,'C992509513646657,TRANSAKCJA KARTĄ PŁATNICZĄ,-24.50
140,01.12.2025,2THELOO WAW NAYAX WARSZAWA,71896902 2102031833 *********2797252,*********2797252,-4.50,Prąd,,01.12.2025,'69124011121111001132898240,NaN,PLN,'C992533520813758,TRANSAKCJA KARTĄ PŁATNICZĄ,-24.50
688,12.07.2025,MANOLIAKIS NIKOLAOS PALIA POLI R,01833522 140833526 *********2797252,*********2797252,-23.41,Papierosy,,11.07.2025,'69124011121111001132898240,NaN,PLN,'C992519221983352,TRANSAKCJA KARTĄ PŁATNICZĄ,-23.41
141,01.12.2025,RELAY 33301 WARSZAWA,01473834 006258600000058 *********2797252,*********2797252,-10.49,Gazety lub czasopisma,,01.12.2025,'69124011121111001132898240,NaN,PLN,'C992533517007134,TRANSAKCJA KARTĄ PŁATNICZĄ,-10.49

In [59]:
mask_exclude = df["Kategoria"] != "Przelew wewnętrzny"

(df.loc[mask_exclude, "Kwota operacji"].sum() + 145_000 + 42_000 + 40_000 + 40_000)/12

np.float64(-10272.344166666668)

In [60]:
mask_include = df["Kategoria"] == "Spłata kredytu / pożyczki"
df.loc[mask_include, "Kwota operacji"].sum()

np.float64(-41905.78)